apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-gateway
  labels:
    app: {{ .Release.Name }}-api-gateway
spec:
  replicas: {{ .Values.apiGateway.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api-gateway
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api-gateway
    spec:
      containers:
        - name: api-gateway
          image: "{{ .Values.global.image.repository }}-api-gateway:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ServiceUrls__OrderService
              value: "http://{{ .Release.Name }}-order-service"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-gateway
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
    - port: {{ .Values.apiGateway.service.port }}
      targetPort: {{ .Values.apiGateway.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-api-gateway
